# Generated by Django 5.0.6 on 2024-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='status',
            field=models.CharField(choices=[('N', 'Новое'), ('A', 'Подтверждено'), ('R', 'Отклонено')], default='N', max_length=1),
        ),
    ]
