# Generated by Django 5.0.6 on 2024-05-21 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_statements_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Введите телефон в формате +7(XXX)-XXX-XX-XX', regex='\\+7\\(\\d\\d\\d\\)-\\d\\d\\d-\\d\\d-\\d\\d')], verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration_number', models.CharField(max_length=15, verbose_name='Государственный регистрационный номер')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('status', models.CharField(choices=[('N', 'Новое'), ('A', 'Подтверждено'), ('R', 'Отклонено')], default='N', max_length=1, verbose_name='Статус')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
        ),
        migrations.DeleteModel(
            name='Statements',
        ),
    ]
