# Generated by Django 5.0.6 on 2024-05-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 17, 56, 1, 369077, tzinfo=datetime.timezone.utc), verbose_name='Дата и время'),
            preserve_default=False,
        ),
    ]
